title: <p align="center"> Prasad G T</p>
logo: /assets/logo.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/prasad-g-t-bb9608b0/">LinkedIn</a> |
  <a href="https://github.com/GTPrasad">GitHub</a>
  
  <br>   
  I'm working as Quality Engineer.
  Learning Data Science from Upgrad.
  <br>
  </p>

theme: jekyll-theme-minimal
